upgrade some deps and yarn
navikt/sykmeldinger pull request #243
Opened 2022-08-26 14:11 UTC by karl-run

2022-08-26 14:45 UTC, MikAoJk approved these changes

2022-08-26 17:00 UTC, MikAoJk requested changes
Ser ut som noe tester ikkje kjører

2022-08-29 11:54 UTC, MikAoJk approved these changes

2022-08-30 11:14 UTC, nuranes approved these changes

2022-09-01 06:37 UTC, merged