add utenlandsk sykmelding
navikt/sykmeldinger pull request #299
Opened 2022-12-16 15:11 UTC by nuranes

2022-12-17 12:16 UTC, MikAoJk approved these changes

2022-12-18 10:14 UTC, karl-run commented on src/components/SykmeldingViews/SykmeldingView/Sections/SykmeldingArbeidsgiverUtenlandsk/AnnenInfoView.tsx
> +                <BodyShort size="small">{sykmelding.utenlandskSykmelding?.land}</BodyShort>
Blir litt rart med denne nullabiliteten siden den allerede er sjekket før denne komponenten rendres, men kan være litt tricky å få med seg type-inferrencen ned hit. Så det får la gå :shrug:

2022-12-18 10:18 UTC, karl-run requested changes

2022-12-18 10:18 UTC, karl-run commented on src/components/SykmeldingViews/SykmeldingView/Sections/SykmeldingArbeidsgiverUtenlandsk/AnnenInfoView.tsx
> +                <BodyShort size="small">{sykmelding.utenlandskSykmelding?.land}</BodyShort>
kom på en annen ting, dette er jo den 3-siffa ISO landskoden, så her vil det jo rendres bare "POL", "SWE" etc. Men vi kunne mappet det om fra landskoder til landstekst i backenden (kankje i zod-schema med refine/transform), så vi slipper vi å shippe alle landskoder+land til frontenden.

2022-12-21 11:17 UTC, karl-run approved these changes

2022-12-21 12:05 UTC, merged