feat/bruker svar
navikt/sykmeldinger pull request #525
Opened 2024-01-24 10:12 UTC by karl-run

- feat: show users svar on kvittering and before submitting (AG)
- test: assert actual answers in e2e for arbeidsledig, annet and arbeidstaker
- test: expect answers in egenmeldingsdager e2e tests

2024-01-24 16:46 UTC, nuranes requested changes

2024-01-24 16:46 UTC, nuranes commented on e2e/fiskere.spec.tsx
> +                    lottEllerHyre: 'Lott',
Skulle det ikkje ha vore `lottEllerHyre: 'Hyre',` her?

2024-01-24 16:46 UTC, nuranes commented on e2e/fiskere.spec.tsx
> +                    lottEllerHyre: 'Lott',
Og `'Begge'` her?

2024-01-24 16:46 UTC, nuranes commented on e2e/fiskere.spec.tsx
> +                    lottEllerHyre: 'Lott',
`Hyre`?

2024-01-25 07:52 UTC, karl-run commented on src/components/Sykmelding/SykmeldingerSykmeldt/Felles/BrukerSvar.tsx
> +            <YesNoAnswer response={brukerSvar.erOpplysningeneRiktige} />
Good catch!

2024-01-25 08:35 UTC, karl-run commented on src/components/Sykmelding/SykmeldingerSykmeldt/Felles/BrukerSvar.tsx
> +            <FiskerLottOgHyreAnswer response={brukerSvar.fisker?.lottOgHyre} />
det var et godt poeng :sweat: jeg tenkte på det men jeg overkompliserte det noe veldig, det blir jo rett å bare flytte den :facepalm:

2024-01-25 11:21 UTC, merged